### ISSUE TITLE
[7.3] PlaySound API changes, toggle options cause error

### ISSUE THREAD

**Issue by Myrroddin** [Phanx/GoFish#5]
`1x GoFish\Options-Options.lua:92: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
[C]: in function `PlaySound'
GoFish\Options-Options.lua:92: in function <GoFish\Options.lua:90>

Locals:
(*temporary) = nil
`
There are several lines in Options.lua that call PlaySound() and all of them will cause an error. I could not find SOUNDKIT versions of SOUND_ON or SOUND_OFF but perhaps you can find something appropriate from [the list](http://www.wowinterface.com/forums/showthread.php?t=55702).

**Comment by armordecai** [comment]
Fixed in 7.3.0.1
