### ISSUE TITLE
Issue mousing over fishing school while mounted. 

### ISSUE THREAD

**Issue by EkaterinaR** [Phanx/GoFish#7]
Hi,
Due, no doubt, to api changes in the pre-patch I get a spectacularly unhelpful error message about usage for line 389, about UnitBuff.  
Replacing 
or (IsMounted() and not (UnitBuff("player", FROSTWOLF_WAR_WOLF) or UnitBuff("player", TELAARI_TALBUK))) 
with:
or (IsMounted() and not (AuraUtil.FindAuraByName(FROSTWOLF_WAR_WOLF, "player") or AuraUtil.FindAuraByName(TELAARI_TALBUK, "player")))
seems to have fixed the issue.

**Comment by Phanx** [comment]
This was already fixed in f94f2350b71fe79f2ab1b1fac06d5c7bbfbc3e85
